import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import styles from './layout.module.css';
import utilStyles from './utils.module.css';
import Image from "next/image";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

const name = 'Usama Israr';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={styles.container}>
          <header className={styles.header}>
            <Link href="/">
              <Image
                priority
                src="/images/profile.png"
                className={utilStyles.borderCircle}
                height={108}
                width={108}
                alt="Usama Israr"
              />
            </Link>
            <h1 className={utilStyles.heading2Xl}>{name}</h1>
            {children}
          </header>
        </div>
      </body>
    </html>
  );
}
